---
title: Vänteläge med Cold genererar felet"DataStoreException Record does not exist"
description: Beskrivning
solution: Experience Manager
product: Experience Manager
applies-to: Experience Manager
keywords: KCS, AEM, kall vänteläge, DataStoreException, Adobe Experience Manager, posten finns inte, fel, varning, varning
resolution: Resolution
internal-notes: https://issues.apache.org/jira/browse/OAK-8202,https://jira.corp.adobe.com/browse/GRANITE-11668
bug: false
article-created-by: Jim Menn
article-created-date: 9/28/2022 2:23:47 PM
article-published-by: Jim Menn
article-published-date: 9/28/2022 5:41:23 PM
version-number: 3
article-number: KA-15610
dynamics-url: https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=5e521024-393f-ed11-9db1-0022480866ad
exl-id: d37d0338-be4f-4660-a4b2-cd1179717e07
source-git-commit: 9c971ee2ceef8f48902d857145545ef173f3752a
workflow-type: tm+mt
source-wordcount: '231'
ht-degree: 0%

---

# Vänteläge med Cold genererar felet&quot;DataStoreException Record does not exist&quot;

## Beskrivning


<b>Miljö</b>
Adobe Experience Manager

<b>Problem</b>
Vänteläge i kylläge med dedikerad fildatastore ger en varning om att det saknas ett blob-ID som liknar felet här:


```
*WARN* standby-run-1 org.apache.jackrabbit.oak.plugins.blob.datastore.DataStoreBlobStore Error occurred while loading bytes from steam while fetching for id f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845#25522

java.util.concurrent.ExecutionException: java.io.IOException: org.apache.jackrabbit.core.data.DataStoreException: Record f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845 does not exist

    at org.apache.jackrabbit.oak.cache.CacheLIRS$Segment.load(CacheLIRS.java:1017) org.apache.jackrabbit.oak-core-spi:1.10.3

...

Caused by: org.apache.jackrabbit.core.data.DataStoreException: Record cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20 does not exist

    at org.apache.jackrabbit.core.data.AbstractDataStore.getRecord(AbstractDataStore.java:59)
```


<b>Orsak</b>
Det här är bara en varning, inte ett fel.

Det beror på att File Datastore inte har något sätt att verifiera om en binär fil finns lokalt, förutom genom att försöka läsa in blob-ID:t.
Om ID:t läses in visas inte den här varningen i loggarna.
Om det inte hittas vet dock vänteläge att det måste synkroniseras, så det är därför du ser den här typen av varning i loggarna.


## Upplösning


<b>Lösning</b>
Detta fungerar som det ska och tyder inte på något problem med fildatalagret.

Följ de här stegen för att bekräfta att blob-ID:t inte saknas:

1. Ta till exempel det exempel på blob-ID som visas som saknat i loggarna (till exempel: `cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`).
2. För det här blob-ID:t i det här exemplet ska filsystemets adress vara: `ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`.
3. Sök i filsystemet i väntelägesinstansen och kontrollera om den namngivna filen finns i arkivet.
4. Inom `/repository/datastore`, använder du `list` (Till exempel: `ls -ald`): `ls -ald ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`.
5. Du bör kunna se filen och bekräfta att blob-ID:t faktiskt inte saknas.
